#!/bin/bash

# Health Check Interval Testing Script
# This script demonstrates health checks running at configured intervals

echo "=========================================="
echo "Health Check Interval Testing"
echo "=========================================="
echo ""

# Test 1: Docker Compose Health Checks
echo "Test 1: Start services and watch health checks"
echo "-----------------------------------------------"
echo "Commands:"
echo "  docker-compose up -d"
echo "  docker events --filter 'event=health_status' &"
echo "  watch -n 1 'docker-compose ps'"
echo ""
echo "Expected: Health checks every 10-15 seconds"
echo "  - postgres: every 10s"
echo "  - redis: every 10s"
echo "  - api-service: every 10s"
echo "  - worker-service: every 15s"
echo ""

# Test 2: Manual health check monitoring
echo "Test 2: Continuously call health endpoint"
echo "-----------------------------------------------"
echo "Run this to see health checks in real-time:"
echo ""
echo "while true; do"
echo "  echo \"[\$(date '+%H:%M:%S')] Checking health...\""
echo "  curl -s http://localhost:8080/actuator/health | jq -r '.status'"
echo "  sleep 5  # Check every 5 seconds"
echo "done"
echo ""

# Test 3: Watch Kubernetes probes
echo "Test 3: Kubernetes health check monitoring"
echo "-----------------------------------------------"
echo "Commands:"
echo "  kubectl get events -w | grep -i probe"
echo "  kubectl get pods -w"
echo ""
echo "Expected: Probe events every 5-15 seconds"
echo "  - Liveness: every 10-15s"
echo "  - Readiness: every 5-10s"
echo ""

# Test 4: Prometheus metrics
echo "Test 4: Monitor health metrics with Prometheus"
echo "-----------------------------------------------"
echo "Query: up{job=\"api-service\"}"
echo "Expected: Metrics updated every 10-15 seconds"
echo ""

echo "=========================================="
echo "Quick Start Test"
echo "=========================================="
echo ""
echo "1. Start services:"
echo "   docker-compose up -d"
echo ""
echo "2. In one terminal, watch Docker health status:"
echo "   watch -n 1 'docker ps --format \"table {{.Names}}\t{{.Status}}\"'"
echo ""
echo "3. In another terminal, monitor health endpoint:"
echo "   while true; do"
echo "     echo \"[\$(date '+%H:%M:%S')]\" && curl -s http://localhost:8080/actuator/health | jq '.'"
echo "     sleep 10"
echo "   done"
echo ""
echo "4. You'll see:"
echo "   - Docker health checks updating every 10-15 seconds"
echo "   - Health endpoint responding with current status"
echo ""
echo "5. Test failure detection:"
echo "   docker-compose stop redis"
echo "   # Watch health checks detect failure within 10-15 seconds"
echo ""

echo "=========================================="
echo "Configuration Summary"
echo "=========================================="
echo ""
echo "Health check intervals are configured in:"
echo ""
echo "1. docker-compose.yaml:"
echo "   api-service:     interval: 10s"
echo "   worker-service:  interval: 15s"
echo ""
echo "2. k8s/api-service-deployment.yaml:"
echo "   livenessProbe:   periodSeconds: 10"
echo "   readinessProbe:  periodSeconds: 5"
echo ""
echo "3. k8s/worker-service-deployment.yaml:"
echo "   livenessProbe:   periodSeconds: 15"
echo "   readinessProbe:  periodSeconds: 10"
echo ""
echo "Remember: Interval is NOT in Java code - it's infrastructure config!"
echo ""

