spring.application.name=worker-service
# --- SERVER ---
server.port=8081

# --- DATASOURCE ---
spring.datasource.url=jdbc:postgresql://localhost:5432/jobdb
spring.datasource.username=jobuser
spring.datasource.password=jobpass
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- REDIS ---
spring.data.redis.host=localhost
spring.data.redis.port=6379

